### ISSUE TITLE
deploy status 

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/matching_contracts#1]
https://github.com/developerfred/gitcoin-grants-subgraph/pull/1

**Comment by mds1** [comment]
Contract is deployed on mainnet and Rinkeby at 0xf2354570bE2fB420832Fb7Ff6ff0AE0dF80CF2c6

**Comment by developerfred** [comment]
Thanks @mds1!
update: https://thegraph.com/explorer/subgraph/developerfred/gitcoin-grants
